services:
  auth-service:
    image: hakimamarullah/api-key-management-service-nestjs:v1.0.0
    container_name: api-key-management-service
    restart: on-failure
    ports:
      -   3002:3002
    env_file:
      -   .env.docker